Al-Tayee/Models/ErrorViewModel.cs
namespace Al_Tayee.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Al-Tayee/Areas/Admin/Controllers/AccountController.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;

namespace Al_Tayee.Areas.Admin.Controllers
{
    public class AccountController : Controller
    {
        private IUserService _user;
        public AccountController(IUserService user)
        {
            _user = user;
        }        

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                await _user.Login(viewModel);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View();
            }
			return View("Admin/Brands/Index");
        }

        public async Task<IActionResult> Logout()
        {
            await _user.Logout();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return RedirectToAction("Login");
        }
    }
}

Al-Tayee/Areas/Admin/Controllers/BrandsController.cs
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;

namespace Al_Tayee.Areas.Admin.Controllers
{
    [Authorize]
    public class BrandsController : Controller
    {
        private IWebHostEnvironment _environment;
        private IBrandsSvc<Brands> _brandsSvc;
        public BrandsController(IWebHostEnvironment environment , IBrandsSvc<Brands> brandsSvc)
        {
            _environment = environment;
            _brandsSvc = brandsSvc;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [Route("Brands/AddBrand")]
        public async Task<ReturnResponse> Create([FromBody] Brands brands)
        {            
            return await _brandsSvc.Add(brands);
        }

        [HttpPost]
        [Route("Brands/AddImages")]
        public string AddImages(List<IFormFile> Images)
        {
            var count = 0;
            var fileName = string.Empty;
            foreach (var image in Images)
            {
                fileName = Path.GetFileName("Img_" + count.ToString() + image.FileName + Guid.NewGuid());
                var filePath = Path.Combine(_environment.ContentRootPath, "wwwroot", "Images", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    image.CopyToAsync(fileStream);
                }
                count++;
            }
            return fileName;
        }

        [HttpPost]
        [Route("Brands/DeleteBrand/{Id}")]
        public async Task<ReturnResponse> Delete(Guid Id)
        {
            return await _brandsSvc.Delete(Id);
        }
        [HttpPost]
        [Route("Brands/GetAllBrands")]
        public async Task<IList<Brands>> GetAll()
        {
            return await _brandsSvc.GetDataList();
        }
    }
}

Al-Tayee/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Al_Tayee.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Al-Tayee/Controllers/HomeController.cs
using Al_Tayee.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Al_Tayee.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Al-Tayee/Areas/Admin/Views/Brands/Index.cshtml
@{
    Layout = "_Layout";
}


<!--begin::Page Vendors Styles(used by this page) -->
<link href="~/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />

<div id="Add_Edit_Brand" class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid" style="display:none">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Add New Brand
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                <form id="BrandForm" class="kt-form kt-form--label-right">
                    <div class="kt-portlet__body">
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Brand Name English:</label>
                                <input type="text" id="BrandNameEntxt" class="form-control req" placeholder="Enter english name">
                                <span class="spnreq" id="BrandNameEntxtreq" style="display:none;">The english name is Required</span>
                            </div>
                            <div class="col-lg-6">
                                <label class="">Brand Name Arabic:</label>
                                <input type="text" id="BrandNameArtxt" class="form-control req" placeholder="Enter arabic number">
                                <span class="spnreq" id="BrandNameArtxtreq" style="display:none;">The arabic name is Required</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label>Brand Logo:</label>
                                <input type="file" id="BrandLogoFile" class="form-control" >
                                <span class="spnreq" id="BrandLogoFilereq" style="display:none;">Image is Required</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <div class="row">
                                <div class="col-lg-6">
                                    <button type="reset" id="Savebtn" class="btn btn-primary">Save</button>
                                    <button type="reset" id="Cancelbtn" class="btn btn-secondary">Cancel</button>
                                </div>
                                <div class="col-lg-6 kt-align-right">
                                    <button type="reset" id="Deletebtn" class="btn btn-danger">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>
        </div>
    </div>
</div>

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Brands
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <div class="dropdown dropdown-inline">
                            <div class="dropdown-menu dropdown-menu-right">
                                <ul class="kt-nav">
                                    <li class="kt-nav__section kt-nav__section--first">
                                        <span class="kt-nav__section-text">Choose an option</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        &nbsp;
                        <a href="#" id="Add_Edit_Brandsbtn" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            New Record
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="kt-portlet__body">

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name English</th>
                        <th>Name Arabic</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Image</td>
                        <td>Brand</td>
                        <td>براند</td>
                        <td nowrap></td>
                    </tr>
                </tbody>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
</div>
@*<script src="~/areas/admin/models/brands/brands.js"></script>*@
@*<script src="~/js/brands/brands.js"></script>*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<!--end::Global Theme Bundle -->
<!--begin::Page Vendors(used by this page) -->
<script src="~/plugins/custom/datatables/datatables.bundle.js" type="text/javascript"></script>

<!--end::Page Vendors -->
<!--begin::Page Scripts(used by this page) -->
<script src="~/js/pages/crud/datatables/advanced/column-rendering.js" type="text/javascript"></script>

<script>
    $(function () {
        alert();
        GetAllData();
    });
    function GetAllData() {
        alert();
        $.ajax({
            url: "/Brands/GetAllBrands",
            type: "GET",
                success: function (data) {
                swal("Success", data.Message, "success");
                $("#Add_Edit_Brand").slideup();
            },
            error: function (err) {
                swal('Oops...', 'Something went wrong!', 'error');
            }
        })
    }
</script>
<script>
    
    function uuidv4() {
        return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
            (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
        );
    }
    var imagesToUpload = []
    $(document).on("click", "#Add_Edit_Brandsbtn", function () {
        $("#Add_Edit_Brand").slideDown('slow');
    });
    $("#BrandLogoFile").change(function (event) {
        $.each(this.files, function (i, item) {
            imagesToUpload.push(item)
        });
        $(this).val(null);        
    })
    var BrandEnName = $("#BrandNameEntxt").val();
    var BrandArName = $("#BrandNameArtxt").val();
    var form = new FormData();
    var Image;
    $(document).on("click", "#Savebtn", function () {  
        let valid = true;
        $('.spnreq').hide();
        $('.req').each(function () {
            if ($(this).val() === "" || $(this).val().trim() === ""){                
                $('#' + $(this).attr('id') + 'req').show();
                valid = false;
            }
        })
        if (imagesToUpload.length == 0) {
            valid = false;
            $('#BrandLogoFilereq').show();
        }        
        if(valid == true){
            $.each(imagesToUpload, function (i, item) {
                var guid = uuidv4();
                Image = "img_" + i + item.name + guid;;
                item.FileName = Image;
                form.append("Images", item);
            })
            $.ajax({
                url: "/Brands/AddImages",
                type: "POST",
                data: form,
                processData: false,
                contentType: false,
                success: function (result) {
                    var brands = {
                        NameEn: BrandEnName,
                        NameAr: BrandArName,
                        Image: result
                    };
                    $.ajax({
                        url: "/Brands/AddBrand",
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify(brands),
                        success: function (data) {
                            swal("Success", data.Message, "success");
                            $("#Add_Edit_Brand").slideup();
                        },
                        error: function (err) {
                            swal('Oops...', 'Something went wrong!', 'error');
                        }
                    })
                },
                error: function (xhr, status, error) {
                    // Handle any errors that occur during the AJAX request
                }
            });
        }
    });
    $(document).on("click", "#Cancelbtn", function () {
    $("#Add_Edit_Brand").slideUp();
    });
    $(document).on("click", "#Deletebtn", function () {
        $("#BrandNameEntxt").val(null);
        $("#BrandNameArtxt").val(null);
        imagesToUpload = [];
        //$("#Add_Edit_Brand").slideUp();
    });
</script>

Al-Tayee/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Al-Tayee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Al_Tayee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/Al_Tayee.styles.css" asp-append-version="true" />*@

    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="~/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.bundle.css" rel="stylesheet" type="text/css" />
    
    <link href="~/sweetalert/sweetalert.css" rel="stylesheet" />

    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->
    <link href="~/css/skins/header/base/light.css" rel="stylesheet" type="text/css" />
    <link href="~/css/skins/header/menu/light.css" rel="stylesheet" type="text/css" />
    <link href="~/css/skins/brand/dark.css" rel="stylesheet" type="text/css" />
    <link href="~/css/skins/aside/dark.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

                <!-- begin:: Aside -->
                <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
                    <div class="kt-aside__brand-logo">
                        <a href="index.html">
                            <img alt="Logo" src="assets/media/logos/logo-light.png" />
                        </a>
                    </div>
                    <div class="kt-aside__brand-tools">
                        <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon points="0 0 24 0 24 24 0 24" />
                                        <path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
                                        <path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
                                    </g>
                                </svg>
                            </span>
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon points="0 0 24 0 24 24 0 24" />
                                        <path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z" fill="#000000" fill-rule="nonzero" />
                                        <path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
                                    </g>
                                </svg>
                            </span>
                        </button>

                        <!--
                        <button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
                        -->
                    </div>
                </div>

                <!-- end:: Aside -->
                <!-- begin:: Aside Menu -->
                <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
                    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
                        <ul class="kt-menu__nav ">
                            <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true">
                                <a href="index.html" class="kt-menu__link ">
                                    <span class="kt-menu__link-icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <polygon points="0 0 24 0 24 24 0 24" />
                                                <path d="M12.9336061,16.072447 L19.36,10.9564761 L19.5181585,10.8312381 C20.1676248,10.3169571 20.2772143,9.3735535 19.7629333,8.72408713 C19.6917232,8.63415859 19.6104327,8.55269514 19.5206557,8.48129411 L12.9336854,3.24257445 C12.3871201,2.80788259 11.6128799,2.80788259 11.0663146,3.24257445 L4.47482784,8.48488609 C3.82645598,9.00054628 3.71887192,9.94418071 4.23453211,10.5925526 C4.30500305,10.6811601 4.38527899,10.7615046 4.47382636,10.8320511 L4.63,10.9564761 L11.0659024,16.0730648 C11.6126744,16.5077525 12.3871218,16.5074963 12.9336061,16.072447 Z" fill="#000000" fill-rule="nonzero" />
                                                <path d="M11.0563554,18.6706981 L5.33593024,14.122919 C4.94553994,13.8125559 4.37746707,13.8774308 4.06710397,14.2678211 C4.06471678,14.2708238 4.06234874,14.2738418 4.06,14.2768747 L4.06,14.2768747 C3.75257288,14.6738539 3.82516916,15.244888 4.22214834,15.5523151 C4.22358765,15.5534297 4.2250303,15.55454 4.22647627,15.555646 L11.0872776,20.8031356 C11.6250734,21.2144692 12.371757,21.2145375 12.909628,20.8033023 L19.7677785,15.559828 C20.1693192,15.2528257 20.2459576,14.6784381 19.9389553,14.2768974 C19.9376429,14.2751809 19.9363245,14.2734691 19.935,14.2717619 L19.935,14.2717619 C19.6266937,13.8743807 19.0546209,13.8021712 18.6572397,14.1104775 C18.654352,14.112718 18.6514778,14.1149757 18.6486172,14.1172508 L12.9235044,18.6705218 C12.377022,19.1051477 11.6029199,19.1052208 11.0563554,18.6706981 Z" fill="#000000" opacity="0.3" />
                                            </g>
                                        </svg>
                                    </span><span class="kt-menu__link-text">Dashboard</span>
                                </a>

                                <a asp-area="Admin" asp-controller="Brands" asp-action="Index" class="kt-menu__link kt-menu__toggle">
                                    <span class="kt-menu__link-icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24" />
                                                <rect fill="#000000" x="4" y="4" width="7" height="7" rx="1.5" />
                                                <path d="M5.5,13 L9.5,13 C10.3284271,13 11,13.6715729 11,14.5 L11,18.5 C11,19.3284271 10.3284271,20 9.5,20 L5.5,20 C4.67157288,20 4,19.3284271 4,18.5 L4,14.5 C4,13.6715729 4.67157288,13 5.5,13 Z M14.5,4 L18.5,4 C19.3284271,4 20,4.67157288 20,5.5 L20,9.5 C20,10.3284271 19.3284271,11 18.5,11 L14.5,11 C13.6715729,11 13,10.3284271 13,9.5 L13,5.5 C13,4.67157288 13.6715729,4 14.5,4 Z M14.5,13 L18.5,13 C19.3284271,13 20,13.6715729 20,14.5 L20,18.5 C20,19.3284271 19.3284271,20 18.5,20 L14.5,20 C13.6715729,20 13,19.3284271 13,18.5 L13,14.5 C13,13.6715729 13.6715729,13 14.5,13 Z" fill="#000000" opacity="0.3" />
                                            </g>
                                        </svg>
                                    </span><span class="kt-menu__link-text">Brands</span>
                                </a>
                                <a asp-area="Admin" asp-controller="Products" asp-action="Index" class="kt-menu__link kt-menu__toggle">
                                    <span class="kt-menu__link-icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24" />
                                                <rect fill="#000000" x="4" y="4" width="7" height="7" rx="1.5" />
                                                <path d="M5.5,13 L9.5,13 C10.3284271,13 11,13.6715729 11,14.5 L11,18.5 C11,19.3284271 10.3284271,20 9.5,20 L5.5,20 C4.67157288,20 4,19.3284271 4,18.5 L4,14.5 C4,13.6715729 4.67157288,13 5.5,13 Z M14.5,4 L18.5,4 C19.3284271,4 20,4.67157288 20,5.5 L20,9.5 C20,10.3284271 19.3284271,11 18.5,11 L14.5,11 C13.6715729,11 13,10.3284271 13,9.5 L13,5.5 C13,4.67157288 13.6715729,4 14.5,4 Z M14.5,13 L18.5,13 C19.3284271,13 20,13.6715729 20,14.5 L20,18.5 C20,19.3284271 19.3284271,20 18.5,20 L14.5,20 C13.6715729,20 13,19.3284271 13,18.5 L13,14.5 C13,13.6715729 13.6715729,13 14.5,13 Z" fill="#000000" opacity="0.3" />
                                            </g>
                                        </svg>
                                    </span><span class="kt-menu__link-text">Products</span>
                                </a>
                            </li>                                                                                    
                        </ul>
                    </div>
                </div>

                <!-- end:: Aside Menu -->
            </div>
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>

                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Al_Tayee - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <a href="~/lib/jquery/dist/jquery.min.map">~/lib/jquery/dist/jquery.min.map</a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <!--begin::Global Theme Bundle(used by all pages) -->    
    <script src="~/plugins/global/plugins.bundle.js"></script>
    <script src="~/js/scripts.bundle.js"></script>

    <script src="~/sweetalert/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>